#!/usr/bin/env bash
# Read and displays /etc/passwd content (show username, id and home only)

FILE="/etc/passwd"
while IFS=: read -r username _ userid _ _ homedir _
do
  echo "$username:$userid:$homedir"
done < $FILE
