#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but for
# the 9th iteration, displays Holberton School and then Hi on a new line.

i=1
while ((i<=10))
do
	if [[ $i != 9 ]]
	then
  		echo "Holberton School"
		((i++))
	else
		echo "Holberton School"
  		echo "Hi"
		((i++))
	fi
done
