#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but for
# the 9th iteration, displays Holberton School and then Hi on a new line.
i=1
while ((i<=20))
do
	case $i in
		4)
		echo "$i"
		echo "bad luck from china"
		((i++))
		;;

		9)
		echo "$i"
		echo "bad luck from Japan"
		((i++))
		;;

		17)
		echo "$i"
		echo "bad luck from Italy"
		((i++))
		;;
		*)
		echo "$i"
		((i++))
		;;
esac
done
