#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, but for
# the 9th iteration, displays Holberton School and then Hi on a new line.
i=1
while ((i<=20))
do
	if [[ $i == 4 ]]
	then
		echo "$i"
  		echo "bad luck from China"
		((i++))
	elif [ $i == 9 ]
	then
		echo "$i"
		echo "bad luck from Japan"
		((i++))
	elif [ $i == 17 ]
	then
		echo "$i"
		echo "bad luck from Italy"
		((i++))
	else
  		echo "$i"
		((i++))
	fi
done
