#!/usr/bin/env bash
# Superstitious numbers: Display numbers from 1 to 20 and displays 
# an special message for 4, 9 and 17 

i=1
while ((i<=20))
do
	case $i in
		4)
		echo "$i"
		echo "bad luck from China"
		((i++))
		;;

		9)
		echo "$i"
		echo "bad luck from Japan"
		((i++))
		;;

		17)
		echo "$i"
		echo "bad luck from Italy"
		((i++))
		;;

		*)
		echo "$i"
		((i++))
		;;
esac
done
